language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 13.7

script:
  - yarn --cwd packages/kryo test
  - yarn --cwd packages/kryo-bson test
  - yarn --cwd packages/kryo-json test
  - yarn --cwd packages/kryo-qs test
#- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
#- ./tools/continuous-deployment.travis.sh

after_script:
  - npx codecov
