language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  # Support policy: all latest and LTS Node versions above 14
  - 14

script:
  - yarn test
#- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
#- ./tools/continuous-deployment.travis.sh

after_script:
  - npx codecov
