language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
- stable
before_install:
- npm install -g typings gulp-cli npm typedoc
script:
- npm test
- chmod +x ./deploy-gh-pages.sh && ./deploy-gh-pages.sh
